spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://118.190.203.107:3306/treasure?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: jubaokj@2019. #dqjbkjasdfASDF8130817
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

#微信配置
wx:
  config:
    app_id: wxad740a938ece9c6d
    appsecret: 693b0514dc0fb577b1852ef719eab96f
    miniapp_id: wx6e2e6aa4fa13a6f0
    miniappsecret: f06389fc9c699f60aad424b146f1e911
  pay:
    key: b3131519b52e377344a6ddeb8106c024
    mch_id: 1516500931
    notifyUrl: http://www.jubaoapp.com:8081/treasure-api/api/appPay/notify

#支付宝配置
pay:
  alipay:
    gatewayUrl: https://openapi.alipay.com/gateway.do #https://openapi.alipaydev.com/gateway.do
    appid: 2019092667857068
    appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCFEF/Lw33VPYdlkikXgbke3jTvDBJmVDRq51W/+9R9xXZAc9Plm3UsNLhbIyX4XY+ENarfIj9dKBwcTbzQRNK+LUoBhuDc+UF9PRDoXXotP92fDbKuAv1mD1qrcJaeRw5qRRxglkb21PR2cuc34u97kZlNHfurvDM6u6pi3AGzQ+L/+v/cUT1Om9PqtI17M6xK8qME2ZIU9Ld/vVnwsMz/Iv0+rKzBVAiq0Qhy72JzkIIVMlE5ypeHbKn+N1ladqSxo9NB+vYjEGiDXkMLIyTswlYKkZjZ5CrtLm2u2Y0+qO9rf3OL+L7RhpRTO5Qu1ujdqHBl9fxg5650oJzNGmzZAgMBAAECggEABGM61Ww3zP0/ZrEAG99SLFtlYXCDds5WACRqpm72XcNSF+P527tZjMCcR50MFnl3TwO6A6uMbVTyQFir3i42yMCTjSNWbNLnPurxkMfsTGursh/wgV5l3qSo97g5rzRmnEh1HBY4dtEk0ncNesFH5koxxOI1Nz94bPpdLu9UOwX4xxPMQysA80a14mzsr/TACXrxNkW4A6P9TVMhT6sh9SywyjR/0916AgdW1OPY9pesJNAK3Ee+kKmy8rPvU8GQ8uyNMm4tJqflEufMYr4FR8uIRp72gfXk7m4z6WOAmtk+BPDYFLrq+w8jOxVXrL6Fb/CrrMDKXc98R3pwh4NdgQKBgQDP7r6cKEZ7jbD7UF/qxfQfAZkBhAckQVZcSOosqZ/cnrPQj7IhSFwmYeGVw46glf37WPpOtMkwFPzqfyO4kVO62aTEgTM2x/8lzrxz4GHuE9ECqVHXE/5hjLljPf7xjB8Uf9Fc5nxgcCyVB2qxtbeQauvyJItCuSqBBXBJkQl06QKBgQCj0vlq0K2/tN/PWLlvTxSrOwS6l5NBAToGPQ1iuoQC8GjIHsYuFHmd3xsteaIqp1vyH9MeFVdO/sjg+VhVXGY8WtbiVNDM4WZZeWpVcNZMT6pbiSSdDvEsBMAbMU7wtndFonxUxZbwVIsgFZwybQQTzZXNGiZ52b+JP3sxemQCcQKBgQCPE0FXJCNzisi39NM7MaDL4QaOU3Gykb7B224+8yzL2uvx255/ZlH6GynlKl2uw+ayl8QMejtheV+aX4eNzXnmvTGyARDjZfR76Ggl98SK1FniUe29Z8WHDBTYY+VUAc21BkpieTomBam3lhXlWBuKJPhbcqfcbpr/kmV0SXdPWQKBgQCWUhUInRiA6s/eq1PjvdWCVPI+4Kx+nkiGxuiMagaNx9jtn8dLKwB5CuoeLRjPOKfWoLsQRJbLZmAehs017kXlJZk9LoQ1KrHGcfFPGu2YMhVoTovpDXfgYy9/BByiJVuF6tVY18FrHrhWJV4gqwVtwlutSkx5zILCxhwdR2eTEQKBgGXuPtGUrCEzSuetI1TgCw+4DbephyOPs+G6wThaTWQLhUA6D7njzdWl+LSDtIfyyXWgjISSxnvxzKItp0L8ocg6H6dXvfOWZEby/4G7OwhETozo34Ty+gOmZgUkqlwBuLFcopLCJVUuDYoPX2wJ6tOLItZipHr9ZhJFoeJ8d5yI
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqSrqWzT7+YJV6wGDNXKOvzZ0xkurGEvTOGv7ih/JWQhqt2j0zygo+YtjEROPD32BpQUJXBhAPIp6Dv2iXMa26EYZi3Q8H3D6qxDvw+aOJ5sYw8KiNil0ylGqLrh+a0TCWdMcR/AjJItrJwWLJsCWpGf4/fAV3xTR8uGY4jCx9ZxggblvtH1jUkFcio2ffn+/+9XLiFT+/2d2xYUYueAVabe4ximzeFsclbPYjYF0O0tWa5e33bGgqhPDakqH4j9gTgb9HS05WgGB769NX+bCP9ekQi849Spo+JLZfj5xgRfMNFvegdKaWtbAILJ90V6r0bfrbvEjLv8+Dejn+15EIwIDAQAB
    returnUrl: http://www.jubaoapp.com:8081/treasure-api/api/ali/return
    notifyUrl: http://www.jubaoapp.com:8081/treasure-api/api/ali/notify